import { StationMeasurements } from '../utils/calculations';

interface OpenScadExportProps {
  stations: StationMeasurements[];
  diameter: number;
  numberOfBlades: number;
}

function generateOpenScadCode(stations: StationMeasurements[], diameter: number, numberOfBlades: number): string {
  // Generate hull operations between adjacent stations
  const connections = stations.slice(0, -1).map((_, index) => `
    // Connect stations ${index + 1} and ${index + 2}
    hull() {
      // Station ${index + 1}
      translate([${stations[index].radius * 1000}, 0, 0])
      rotate([${stations[index].setting}, 0, 0])  // Changed rotation axis
      linear_extrude(height=${stations[index].width * 1000}, center=true)
      scale([${stations[index].chord * 1000}, ${stations[index].thickness * 1000}, 1])
      translate([-0.5, 0, 0])  // Center the airfoil
      airfoil();

      // Station ${index + 2}
      translate([${stations[index + 1].radius * 1000}, 0, 0])
      rotate([${stations[index + 1].setting}, 0, 0])  // Changed rotation axis
      linear_extrude(height=${stations[index + 1].width * 1000}, center=true)
      scale([${stations[index + 1].chord * 1000}, ${stations[index + 1].thickness * 1000}, 1])
      translate([-0.5, 0, 0])  // Center the airfoil
      airfoil();
    }`).join('\n');

  return `// Wind Turbine Blade OpenSCAD Model
// Generated by Wind Turbine Propeller Designer
// Dimensions in millimeters

// NACA 4412 airfoil profile (normalized coordinates)
// Mathematically accurate implementation with 4% camber at 40% chord, 12% thickness
module airfoil() {
    // Generate NACA 4412 coordinates
    // Parameters: m=0.04 (4% camber), p=0.4 (camber at 40%), t=0.12 (12% thick)
    m = 0.04;
    p = 0.4;
    t = 0.12;

    polygon(points=[
        // Upper surface (trailing edge to leading edge)
        [1.0000, 0.0013], [0.9500, 0.0096], [0.9000, 0.0175], [0.8000, 0.0312],
        [0.7000, 0.0424], [0.6000, 0.0509], [0.5000, 0.0562], [0.4000, 0.0584],
        [0.3000, 0.0571], [0.2500, 0.0549], [0.2000, 0.0517], [0.1500, 0.0471],
        [0.1000, 0.0408], [0.0750, 0.0365], [0.0500, 0.0314], [0.0250, 0.0246],
        [0.0125, 0.0200], [0.0000, 0.0000],
        // Lower surface (leading edge to trailing edge)
        [0.0125, -0.0148], [0.0250, -0.0186], [0.0500, -0.0234], [0.0750, -0.0264],
        [0.1000, -0.0285], [0.1500, -0.0310], [0.2000, -0.0319], [0.2500, -0.0315],
        [0.3000, -0.0301], [0.4000, -0.0262], [0.5000, -0.0213], [0.6000, -0.0161],
        [0.7000, -0.0111], [0.8000, -0.0067], [0.9000, -0.0032], [0.9500, -0.0017],
        [1.0000, -0.0007]
    ]);
}

// Hub connection module
module hub_mount() {
    union() {
        // Base cylinder
        cylinder(h=50, r1=30, r2=25, center=true);
        
        // Transition to first airfoil
        hull() {
            translate([0, 0, 0])
            cylinder(h=${stations[0].width * 1000}, r=25, center=true);
            
            translate([${stations[0].radius * 1000}, 0, 0])
            rotate([${stations[0].setting}, 0, 0])
            linear_extrude(height=${stations[0].width * 1000}, center=true)
            scale([${stations[0].chord * 1000}, ${stations[0].thickness * 1000}, 1])
            translate([-0.5, 0, 0])
            airfoil();
        }
    }
}

// Main blade assembly
module blade() {
    // Rotate the entire blade to match visualization orientation
    rotate([0, 90, 0])
    union() {
        // Hub mount
        hub_mount();
        
        // Blade sections and connections
        ${connections}
    }
}

// Generate the blade
blade();

/* 
Printing Instructions:
1. Orient the blade vertically (along Z-axis) for best layer adhesion
2. Use supports for overhanging sections
3. Recommended infill: 20-30%
4. Layer height: 0.2mm or less for better surface finish
5. Consider splitting the blade into sections for larger prints

Blade Specifications:
- Total blade length: ${(diameter/2 * 1000).toFixed(1)}mm
- Number of stations: ${stations.length}
- Root chord: ${(stations[0].chord * 1000).toFixed(1)}mm
- Tip chord: ${(stations[stations.length-1].chord * 1000).toFixed(1)}mm
- Root angle: ${stations[0].setting.toFixed(1)}°
- Tip angle: ${stations[stations.length-1].setting.toFixed(1)}°
*/

// To create multiple blades, uncomment and modify:
/*
module complete_turbine() {
    for(i = [0:${360/numberOfBlades}:359]) {
        rotate([0, 0, i])
        blade();
    }
}
complete_turbine();
*/
`;
}

export function OpenScadExport({ stations, diameter, numberOfBlades }: OpenScadExportProps) {
  const openScadCode = generateOpenScadCode(stations, diameter, numberOfBlades);
  
  const handleDownload = () => {
    const blob = new Blob([openScadCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'wind_turbine_blade.scad';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white shadow-sm ring-1 ring-gray-900/5 rounded-xl p-6">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold">OpenSCAD Export</h2>
        <button
          onClick={handleDownload}
          className="btn-primary"
        >
          Download OpenSCAD File
        </button>
      </div>
      <div className="mt-4">
        <pre className="bg-gray-50 p-4 rounded-lg overflow-x-auto text-sm">
          <code>{openScadCode}</code>
        </pre>
      </div>
      <div className="mt-4 text-sm text-gray-600">
        <h3 className="font-medium mb-2">3D Printing Tips:</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li>Print vertically for better layer adhesion</li>
          <li>Enable supports for overhanging sections</li>
          <li>Use 20-30% infill for structural integrity</li>
          <li>Layer height: 0.2mm or less for better surface finish</li>
          <li>Consider PETG or ABS for outdoor durability</li>
          <li>For large blades, consider printing in sections</li>
        </ul>
      </div>
    </div>
  );
} 